### ISSUE TITLE
Should we become an OGC Community Standard?

### ISSUE THREAD

**Issue by jbants** [radiantearth/stac-psc#2]
## Background
Since STAC aligns with OGC API Features, we should make it official and become an OGC community standard.
https://www.ogc.org/standards/community/#:~:text=A%20Community%20standard%20is%20an,of%20the%20OGC%20Standards%20Baseline.

## Proposal
Submit OGC Community standard documents for the STAC **and**  STAC API specifications.

https://github.com/opengeospatial/templates/blob/master/charter_templates/community_std_work_item.adoc

## Additions
STAC Spec Letter
https://gist.github.com/jbants/374f0cf00ad43266fb2ec34fad0b4b2b

STAC API Spec Letter
https://gist.github.com/jbants/88afecbb8017f5b73a4bedfe7b9c3f53

**Comment by m-mohr** [comment]
+1

**Comment by lossyrob** [comment]
+1

**Comment by jbants** [comment]
I've added the letters as Gists. GitHub renders them nicely.

STAC Spec Letter
https://gist.github.com/jbants/374f0cf00ad43266fb2ec34fad0b4b2b

STAC API Spec Letter
https://gist.github.com/jbants/88afecbb8017f5b73a4bedfe7b9c3f53

**Comment by m-mohr** [comment]
@jbants One question regarding the following:

> Will the contributor retain intellectual property rights?
>
>    ❏ Yes
>
>    ✓ No
>
>If yes, the contributor will be required to work with OGC staff to properly attribute the submitter’s intellectual property rights.
>
>If no, the contributor will assign intellectual property rights to the OGC.

Are we sure we hand over intellectual property to OGC? I'm not sure we can just transfer it to OGC. It's not even 100% clear who has the current rights. Radiant Earth? All contributors? In both cases, we'd need official agreement from them, right? Maybe we should tick "Yes".

**Comment by m-mohr** [comment]
See https://www.ogc.org/de/requests/ogc-seeks-public-comment-on-adoption-of-stac-and-stac-api-as-community-standards/
